### ISSUE TITLE
Allow PrimeHub System Admin to add images to any group

### ISSUE THREAD

**Issue by DaveFlynn** [InfuseAI/crane#26]
PrimeHub Integration Feature Request:

Allow a PrimeHub System-level Administrator to add images to ANY group.
Logic: A system level admin should have the highest privileges, including all those of Group Admin.

**Comment by aar0nTw** [comment]
Need patch https://github.com/InfuseAI/primehub-console/blob/c3b245d79c18171665106d2cf0ff1b349be1c770/packages/graphql-server/src/resolvers/image.ts#L23
